spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://localhost:3306/book_management
    username: root
    password: root
    
mybatis:
  mapper-locations:
  - /maapers/*.xml
  
jwt:
  secret: m0FbJ9avbZB0B9wFgfHr7jgN6hzGQpDNxvR9K5UQKdvgIqjsCOpEWJyYTpNET3yS